#!/bin/bash
#
#       copy this script to /etc/rc.d/init.d/rb_nr_agent
#
#
# chkconfig: 345 70 30
# description: NewRelic Agent Plugin for redborder platform
# processname: rb_nr_agent
#

RETVAL=0
prog="rb_nr_agent"
executable="newrelic_example_agent"
LOCKFILE=/var/lock/subsys/$prog

. /etc/init.d/functions

start() {
        if [ -f $LOCKFILE ]; then
          echo "$prog is currently running"
        else
          echo -n "Starting $prog: "
          nohup /opt/newrelic/newrelic/newrelic_example_agent 2> /dev/null &
          RETVAL=$?
          [ $RETVAL -eq 0 ] && touch $LOCKFILE && echo_success
          echo
        fi
        return $RETVAL
}
stop() {
        echo -n "Shutting down $prog: "
        #action killproc $prog

        if [ -f $LOCKFILE  ] ; then
          PID=$(ps aux | grep $executable | grep -v grep | awk {'print $2'})
          kill $PID
          rm -f $LOCKFILE
        else
          echo_failure; failure  
        fi
        RETVAL=$?
        [ $RETVAL -eq 0 ] && echo_success
        echo
        return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        if [ -f $LOCKFILE ]; then
          echo "$prog is running"
        else
          echo "$prog is stopped"
        fi
        ;;
    restart)
        stop
        start
        ;;
  #  reload)
  #      <cause the service configuration to be reread, either with
  #      kill -HUP or by restarting the daemons, in a manner similar
  #      to restart above>
  #      ;;
  #  condrestart)
  #      <Restarts the servce if it is already running. For example:>
  #      [ -f /var/lock/subsys/<service> ] && restart || :
  #  probe)
  #      <optional.  If it exists, then it should determine whether
  #      or not the service needs to be restarted or reloaded (or
  #      whatever) in order to activate any changes in the configuration
  #      scripts.  It should print out a list of commands to give to
  #      $0; see the description under the probe tag below.>
  #      ;;
    *)
        echo "Usage: <servicename> {start|stop|status}"
        exit 1
        ;;
esac
exit $?
