#!/bin/bash
#
#       copy this script to /etc/rc.d/init.d/rb_nr_agent
#
#
# chkconfig: 345 70 30
# description: NewRelic Agent Plugin for redborder platform
# processname: rb_nr_agent
#

RETVAL=0
prog="rb_nr_agent"
executable="newrelic_redborder_agent"

. /etc/init.d/functions

start() {
        RESULT = `ps aux | grep $executable | grep -c -v grep`
        if [ "${RESULT:-null}" -ge "1" ]; then
          echo "$prog is currently running"
        else
          echo -n "Starting $prog: "
          nohup /opt/newrelic_rb_plugin/newrelic_redborder_agent  > /dev/null &
          RETVAL=$?
          if [ $RETVAL -eq 0 ]; then
           echo_success
          else
           echo_failure; failure
           RETVAL=1
          fi
          echo
        fi
        return $RETVAL
}
stop() {
      if [ "${RESULT:-null}" -ge "1" ]; then
        echo -n "Shutting down $prog: "
          PID=$(ps aux | grep $executable | grep -v grep | awk {'print $2'} > /dev/null)
          kill -9 $PID
        else
          echo "$executable is running"
          echo_failure; failure
        fi
        RETVAL=$?
        [ $RETVAL -eq 0 ] && echo_success
        echo
        return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
    RESULT=`ps aux | grep $executable | grep -c -v grep`
    if [ "${RESULT:-null}" -ge "1" ]; then
        echo "$executable not running"
        RETVAL=1
    else
        echo "$executable is running"
        RETVAL=0
    fi
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: <servicename> {start|stop|status}"
        exit 1
        ;;
esac
exit $?
