#!/bin/bash

colors=1

if [ -d /opt/rb/etc/rb_check.d ]; then
  for n in $(ls /opt/rb/etc/rb_check.d/*.sh 2>/dev/null); do
    source $n
  done
fi

function print_result(){
  if [ "x$1" == "x0" ]; then
    e_ok
  else
    e_fail
    shift
    [ "x$*" != "x" ]
  fi
}

function e_ok() {
  if [ $colors -eq 0 ]; then
    echo -n "      "
  else
    $MOVE_TO_COL
  fi
  echo -n "["
  set_color green
  echo -n $"  OK  "
  set_color norm
  echo -n "]"
  echo -ne "\r"
  echo
  return 0
}

function e_fail() {
  EXITRET=1
  if [ $colors -eq 0 ]; then
    echo -n "      "
  else
    $MOVE_TO_COL
  fi
  echo -n "["
  set_color red
  echo -n $"FAILED"
  set_color norm
  echo -n "]"
  echo -ne "\r"
  echo
  return 1
}

function set_color() {
  if [ "x$BOOTUP" != "xnone" -a $colors -eq 1 ]; then
    green="echo -en \\033[1;32m"
    red="echo -en \\033[1;31m"
    yellow="echo -en \\033[1;33m"
    orange="echo -en \\033[0;33m"
    blue="echo -en \\033[1;34m"
    black="echo -en \\033[1;30m"
    white="echo -en \\033[255m"
    cyan="echo -en \\033[0;36m"
    purple="echo -en \\033[0;35m"
    browm="echo -en \\033[0;33m"
    gray="echo -en \\033[0;37m"
    norm="echo -en \\033[1;0m"
    eval \$$1
  fi
}

service="$1"

[ ! -f /opt/rb/etc/$service.list ] && echo "Detecting where $service is running ..."
node=$(hostname)
if [ "x$node" != "x" ]; then
  echo -n "Service "
  set_color blue
  echo -n "$service "
  set_color norm
  echo    "running on"
  printf "  - %-85s " $node
  out=$(rb_manager_ssh.sh $node "service $service status &>/dev/null; echo \$?")
  if [ "x$out" == "x0" ]; then
    print_result 0
    running=1
  else
    print_result 1 "ERROR: Service $service is not running on $n and it should"
    running=0
  fi
  ret=0
else
  printf "%-90s" "Service $service not enabled anywhere"
  print_result 0
  ret=1
fi

exit $running
