#!/bin/sh

SERVICE="$1"
RESULT=`ps aux | grep ${SERVICE} | grep -c -v grep`
if [ "${RESULT:-null}" -le "2" ]; then
    echo "${SERVICE} not running"
    RETVAL=1
else
    echo "running: ${SERVICE}"
    RETVAL=0
fi

exit "$RETVAL"
